<?php
define('AWS_API_KEY', 'AKIAIOICYIAS27AA7A3A');
define('AWS_API_SECRET_KEY', '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');
define('AWS_ASSOCIATE_TAG', 'ASSOCIATE TAG');
define('AWS_ANOTHER_ASSOCIATE_TAG', 'ANOTHER ASSOCIATE TAG');

